### ISSUE TITLE
Sample apache config

### ISSUE THREAD

**Issue by gsaslis** [vube/vagrant-catalog#1]
Hi there, 

tried installing this on apache, but i must have something wrong in my apache2 vhost config, or my config.php (i just used the config.php.dist though), so I could really use some help on setting this up properly. 

I can get the homepage to show up correctly and I followed your suggested path structure, so i can see the orgname in the list of sub-directories. My problem is when I actually click on the orgname, i get a 404 error... : / 

Here is my vhost config: 

```
<VirtualHost myhost.mydomain:80>
  ServerName myhost.mydomain
  ErrorLog /var/log/apache2/vc_error_log
  CustomLog /var/log/apache2/vc_access_log combined
  DocumentRoot /srv/vagrant-catalog
  DirectoryIndex index.php

  <Directory "/srv/vagrant-catalog">
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
    Order deny,allow
    Allow from all
  </Directory>

</VirtualHost>
```

Thanks in advance!

**Comment by dstapp** [comment]
Did you try setting AllowOverride to all in order for mod_rewrite to work correctly?

**Comment by gsaslis** [comment]
I did (and, by doing so, i found that it was originally disabled), but even
after enabling

```
a2enmod rewrite
```

and setting AllowOverride to all, i still couldn't get the link to work...
still same error...

Is there a list of requirements somewhere (e.g. any other apache modules I
need to have enabled, etc) ?

**Comment by ross-p** [comment]
Make sure you restart Apache after you set AllowOverride All.

My httpd.conf looks like this for my virtualhost, very similar to yours but I have "AllowOverride All"

The only other thing that comes to mind is that all the rewrite rules are in an .htaccess file, so if there is some server config that allows .htaccess files, make sure that is enabled.

``` text
<VirtualHost *:80>
    ServerName  vagrant.example.com
    ServerAdmin support@example.com
    DocumentRoot /var/www/vagrant.example.com/
    ErrorLog "| /usr/sbin/rotatelogs /var/log/apache2/vagrant.example.com.error_log 300"
    CustomLog "| /usr/sbin/rotatelogs /var/log/apache2/vagrant.example.com.combined_log 300" vhost_combined
    <Directory /var/www/vagrant.example.com/>
        AllowOverride All
    </Directory>
</VirtualHost>
```

**Comment by gsaslis** [comment]
Thanks Ross, will try to look into the .htaccess rewrites when I get some
time... Thanks anyway!

**Comment by ross-p** [comment]
I'm going to create a new feature issue saying to make a full end-to-end example of this, and I'll include things like necessary Apache configs there, and close this issue.

**Comment by gsaslis** [comment]
sure - that sounds great! :thumbsup:

**Comment by ross-p** [comment]
@gsalis https://github.com/xclusv/vagrant-boxer-example

**Comment by gsaslis** [comment]
great stuff! I'll check it out as soon as I find some time over the next week or so! Thanks!
